....
spec:
  containers:
  - image: wordpress:4.7.3-apache
    name: wordpress
    env:
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-password
          key: password
....


spec:
    containers:
    - image: wordpress:4.7.3-apache
      name: wordpress
      volumeMounts:
      - name: secret-volume
        mountPath: "/etc/secret-data"
        readOnly: true
    volumes:
    - name: secret-volume
      secret:
        secretName: my-password
  ....